version: '2'
services:
  mongo: # https://hub.docker.com/_/mongo/
    image: mongo:3.3.15
    ports:
     - "27017:27017"
  neo4j: # https://hub.docker.com/_/neo4j/
    image: neo4j:3.0.6
    ports:
     - "7474:7474"
     - "7687:7687"
    environment:
     - NEO4J_AUTH=none
  tomcat: # https://hub.docker.com/_/tomcat/
    build: ./tomcat
    ports:
     - "8080:8080"
    volumes:
     - /opt/openconjurer:/usr/local/tomcat/webapps/openconjurer
